// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kwdqdaujgmdhantindcp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt3ZHFkYXVqZ21kaGFudGluZGNwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDAwODQsImV4cCI6MjA3MzMxNjA4NH0.UvgWPAjA2iSsSQ2QLPSXonxr51C8SgdGgp1xlSKHLWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});